version: '3.11'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: k8s_web_app:${K8S_WEB_APP_VERSION:-latest}
    restart: always
    env_file:
      - .env
    labels:
      # Enables traefik for this container.
      - traefik.enable=true
      - traefik.http.routers.k8s_web_app.rule=Host(`${K8S_WEB_APP_TRAEFIK_HOST:-k8s_web_app.localhost}`)
      - traefik.http.routers.k8s_web_app.entrypoints=http
      - traefik.http.routers.k8s_web_app.service=k8s_web_app
      - traefik.http.services.k8s_web_app.loadbalancer.server.port=${K8S_WEB_APP_PORT:-8000}
    networks:
      - default
      - traefik-shared
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      K8S_WEB_APP_HOST: 0.0.0.0
      K8S_WEB_APP_DB_HOST: k8s_web_app-db
      K8S_WEB_APP_DB_PORT: 5432
      K8S_WEB_APP_DB_USER: k8s_web_app
      K8S_WEB_APP_DB_PASS: k8s_web_app
      K8S_WEB_APP_DB_BASE: k8s_web_app
      K8S_WEB_APP_REDIS_HOST: k8s_web_app-redis

  db:
    image: postgres:13.8-bullseye
    hostname: k8s_web_app-db
    environment:
      POSTGRES_PASSWORD: "k8s_web_app"
      POSTGRES_USER: "k8s_web_app"
      POSTGRES_DB: "k8s_web_app"
    volumes:
      - k8s_web_app-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U k8s_web_app
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: k8s_web_app:${K8S_WEB_APP_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      K8S_WEB_APP_DB_HOST: k8s_web_app-db
      K8S_WEB_APP_DB_PORT: 5432
      K8S_WEB_APP_DB_USER: k8s_web_app
      K8S_WEB_APP_DB_PASS: k8s_web_app
      K8S_WEB_APP_DB_BASE: k8s_web_app
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "k8s_web_app-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    hostname: "k8s_web_app-zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"
    healthcheck:
      test: zkServer.sh status
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  k8s_web_app-db-data:
    name: k8s_web_app-db-data

networks:
  # Network for traefik.
  traefik-shared:
    name: traefik-shared
