version: '3.11'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: backend:${backend_VERSION:-latest}
    restart: always
    env_file:
      - .env
    labels:
      # Enables traefik for this container.
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`${backend_TRAEFIK_HOST:-backend.localhost}`)
      - traefik.http.routers.backend.entrypoints=http
      - traefik.http.routers.backend.service=backend
      - traefik.http.services.backend.loadbalancer.server.port=${backend_PORT:-8000}
    networks:
      - default
      - traefik-shared
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      backend_HOST: 0.0.0.0
      backend_DB_HOST: backend-db
      backend_DB_PORT: 5432
      backend_DB_USER: backend
      backend_DB_PASS: backend
      backend_DB_BASE: backend
      backend_REDIS_HOST: backend-redis

  db:
    image: postgres:13.8-bullseye
    hostname: backend-db
    environment:
      POSTGRES_PASSWORD: "backend"
      POSTGRES_USER: "backend"
      POSTGRES_DB: "backend"
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U backend
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: backend:${backend_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      backend_DB_HOST: backend-db
      backend_DB_PORT: 5432
      backend_DB_USER: backend
      backend_DB_PASS: backend
      backend_DB_BASE: backend
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "backend-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    hostname: "backend-zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"
    healthcheck:
      test: zkServer.sh status
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  backend-db-data:
    name: backend-db-data

networks:
  # Network for traefik.
  traefik-shared:
    name: traefik-shared
